### ISSUE TITLE
WWW and no WWW URL officinerobotiche.it

### ISSUE THREAD

**Issue by katodo** [officinerobotiche/task-other#1]
If user digit officinerobotiche.it it must be redirected on www.officinerobotiche.it, in this moment a "It works!" page is displayed with officinerobotiche.it URL

**Comment by bobboteck** [comment]
@rbonghi have a tool to set this feature

**Comment by rbonghi** [comment]
To solve this issue I have to change a configuration on Apache 

Raffaello Bonghi

**Comment by rbonghi** [comment]
fixed: http://officinerobotiche.it
@guiott @katodo @bobboteck
