### ISSUE TITLE
All ROS software called "ros_" before name

### ISSUE THREAD

**Issue by rbonghi** [officinerobotiche/task-other#3]
I propose a new name order for all ROS repositories. I would like to use **ros_** before software name.

New name for repositories:
- https://github.com/officinerobotiche/serial_bridge in **ros_serial_bridge**
- https://github.com/officinerobotiche/robot_teleoperation_ros **ros_robot_teleoperation**
- https://github.com/officinerobotiche/myzharbot_robot_ros in **ros_robot_myzharbot**
- https://github.com/officinerobotiche/example_robot_ros in **ros_robot_example**
- https://github.com/officinerobotiche/robot_wandering_demo_ros in **ros_robot_demo_wandering**

cc @Myzhar

**Comment by Myzhar** [comment]
+1
Il 28/Mar/2015 10:32 "Raffaello Bonghi" notifications@github.com ha
scritto:

**Comment by katodo** [comment]
+1

**Comment by bobboteck** [comment]
Sorry, but the "serial_bridge" is only for ROS?
I remeber not!

**Comment by Myzhar** [comment]
The serial_bridge is the "bridge" between ROS and uNav ^_^

2015-03-31 12:18 GMT+02:00 Bobboteck notifications@github.com:

> Sorry, but the "serial_bridge" is only for ROS?
> I remeber not!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/officinerobotiche/task-other/issues/3#issuecomment-88029583
> .

## 

_Walter "Myzhar" Lucetti_

email myzhar@robot-home.it
web: _www.robot-home.it http://www.robot-home.it/ - www.opencv.it
http://www.opencv.it/_
project:  http://myzharbot.robot-home.it

**Comment by rbonghi** [comment]
thx @Myzhar
